runtime: python27
threadsafe: true


env_variables:
  ALLOWED_HOSTS: "*"


inbound_services:
- warmup


handlers:
- url: /_ah/(mapreduce|queue|warmup).*
  script: randnumgen.wsgi.application
  login: admin
- url: /static
  static_dir: static/

- url: /.*
  script: randnumgen.wsgi.application


libraries:
- name: django
  version: "1.11"
