# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-12 20:03
from __future__ import unicode_literals

import djangae.fields.charfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsedNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', djangae.fields.charfields.CharField(max_length=1500)),
            ],
        ),
    ]
